metricbeat-playbook.yml
---
- name: installing and launching metricbeat
  hosts: webservers
  become: true
  tasks:

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install filebeat deb (metricbeat)
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: copy file from ansible container to web server
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: metricbeat modules enable docker

  - name: Run metricbeat setup
    command: metricbeat setup

  - name: start metricbeat service
    command: service metricbeat start

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes